# Generated by Django 4.2.2 on 2023-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_complexity', models.CharField(max_length=100)),
                ('space_complexity', models.CharField(max_length=100)),
                ('best_case', models.CharField(max_length=100)),
                ('worst_case', models.CharField(max_length=100)),
                ('average_case', models.CharField(max_length=100)),
                ('code', models.TextField()),
            ],
        ),
    ]
