# Generated by Django 4.2.2 on 2023-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort_visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='method',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
