# Generated by Django 4.2.2 on 2023-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort_visualizer', '0002_sort_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sort',
            name='average_case',
        ),
        migrations.AlterField(
            model_name='sort',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
