# Generated by Django 4.2.2 on 2023-06-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort_visualizer', '0003_remove_sort_average_case_alter_sort_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sort',
            name='code',
        ),
    ]
