# Generated by Django 4.2.2 on 2023-06-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort_visualizer', '0004_remove_sort_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
