[package]
name = "my_web_server"
version = "0.1.0"
authors = ["Aksidion Kreimben <aksidion@kreimben.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.74"
rocket = "0.4.10"
curl = "0.4.42"
