# Generated by Django 4.2.1 on 2023-05-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_to_ascii_art', '0003_imageconvertingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconvertingresult',
            name='compress_ratio',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
    ]
