# Generated by Django 4.1.4 on 2022-12-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_value', models.CharField(max_length=8)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(max_length=100)),
                ('region_name', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('timezone', models.CharField(max_length=100)),
            ],
        ),
    ]
