# Generated by Django 4.1.7 on 2023-03-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatter",
            name="city",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="chatter",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="chatter",
            name="region_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="chatter",
            name="timezone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
