# Generated by Django 4.2.1 on 2023-06-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_error', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorstatus',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Error Statuses'},
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='ip_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='errorstatus',
            name='user_agent',
            field=models.TextField(),
        ),
    ]
