# Generated by Django 4.0.6 on 2022-07-26 12:55

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_file_post_status"),
    ]

    operations = [
        migrations.DeleteModel(name="UploadedFile", ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
