# Generated by Django 4.1.1 on 2022-09-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_alter_post_category_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published')], default='drafted',
                                   max_length=10),
        ),
        migrations.CreateModel(
            name='SubmittedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='blog.post')),
            ],
            options={
                'verbose_name': 'File in post',
                'verbose_name_plural': 'Files in post',
                'get_latest_by': ['-updated_at'],
            },
        ),
    ]
