# Generated by Django 4.1.1 on 2022-09-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_submittedfile_download_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('continent_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('country_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=1000, null=True)),
                ('download_request_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Downloader',
                'verbose_name_plural': 'Downloaders',
                'get_latest_by': ['-download_request_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='submittedfile',
            options={'get_latest_by': ['-updated_at'], 'verbose_name': 'Submitted File', 'verbose_name_plural': 'Submitted Files'},
        ),
    ]
