# Generated by Django 4.1.1 on 2022-09-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_downloader_alter_submittedfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloader',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='downloaders', to='blog.submittedfile'),
            preserve_default=False,
        ),
    ]
