# Generated by Django 4.1.1 on 2022-09-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_downloader_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloader',
            name='continent_name',
        ),
    ]
