# Generated by Django 4.1.4 on 2022-12-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_options_alter_post_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
