export const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies arcu vel neque hendrerit mollis. Etiam ut metus fermentum, fringilla ante non, lobortis erat. Duis sagittis tortor rhoncus finibus malesuada. Nullam condimentum, nibh in vehicula ultricies, risus nunc auctor ipsum, fringilla egestas metus quam eget tellus. Morbi finibus erat non est pulvinar, eu venenatis tortor fermentum. Nam egestas tempor ligula, ut vulputate velit dignissim at. Nunc volutpat volutpat convallis. Donec est nulla, sollicitudin et velit eget, scelerisque interdum est. Nunc non lorem interdum, feugiat velit sed, consectetur dolor. Vestibulum quis sem venenatis, placerat tellus sed, porttitor ipsum. In molestie ornare lorem, eget rhoncus nulla porttitor et. Donec bibendum, eros vel auctor dictum, lorem massa malesuada ante, in blandit enim dolor et dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse enim leo, ornare id convallis a, mollis eu est. Fusce hendrerit nisi sit amet consectetur lobortis. Phasellus ut vehicula dolor.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla faucibus, nibh et suscipit fringilla, mauris augue volutpat tellus, nec ullamcorper mi nisi vitae odio. Sed auctor rhoncus ante in sodales. Fusce porta mi et quam dictum lacinia. Praesent a placerat mi. Maecenas ut leo id odio consequat convallis. Maecenas vulputate vehicula ex, eu bibendum ligula.

Proin consequat nisl sed risus iaculis dignissim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed nunc odio, tincidunt non blandit eu, viverra eget diam. Donec volutpat, dui quis mattis sodales, orci felis rhoncus est, vitae consectetur odio nibh vel lorem. In hac habitasse platea dictumst. In sit amet malesuada tellus. Pellentesque aliquam elementum diam, nec faucibus est. Sed sed efficitur ipsum. Donec non dui aliquet, faucibus diam ut, rhoncus ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce congue pretium varius. Vivamus accumsan vehicula condimentum.

Vestibulum in euismod urna. Cras non ex velit. Nunc sit amet consectetur leo. Duis et libero ligula. Quisque ut porttitor arcu. Morbi porttitor rutrum leo non commodo. Integer facilisis augue vitae magna tempus sagittis. Aliquam vel diam non nisi aliquet scelerisque sollicitudin ut quam. Donec nunc tellus, luctus in tempus sit amet, maximus eu augue. Mauris id enim urna. Curabitur malesuada id quam at laoreet. Curabitur dapibus sem a massa suscipit, eu imperdiet dolor condimentum. Aenean neque neque, dignissim vitae venenatis ut, mollis sed tortor.

Nullam efficitur eleifend tellus nec porttitor. Phasellus eget quam arcu. Aenean id convallis elit. Praesent et justo pulvinar nunc accumsan semper. Pellentesque in pharetra enim, euismod dapibus dolor. Etiam mollis mauris nec eros bibendum elementum. Nulla lectus lacus, ultrices eu nunc vitae, mollis mattis massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut ipsum at arcu malesuada gravida. Nullam at laoreet augue, non fringilla eros. Duis nibh nibh, interdum in varius non, pellentesque vel nulla.

Donec hendrerit ante justo, in viverra augue ultricies et. Morbi elementum urna eget turpis sagittis ultrices. Etiam malesuada massa nisi, sed ullamcorper metus sagittis sed. Sed ac neque eu velit pellentesque scelerisque. Mauris eu cursus libero. Fusce ac mollis erat. Pellentesque ornare mattis mi, ac vehicula quam. Curabitur maximus eros finibus scelerisque viverra. Donec ac ultrices diam, non sodales nibh. Fusce turpis tellus, molestie sed consequat eu, sagittis eu diam. Nullam convallis porttitor odio eu rutrum. Nunc faucibus lobortis orci vitae laoreet. Integer non orci felis. Ut tristique tortor et massa cursus, a sollicitudin tellus lacinia. Phasellus ac urna nisl. Ut mauris lorem, lacinia a enim sit amet, dictum cursus lectus.

Mauris faucibus aliquam risus, id lobortis nisl aliquet sed. Mauris hendrerit malesuada dignissim. Pellentesque mauris lectus, hendrerit vitae dignissim id, luctus in felis. Morbi eleifend felis non vulputate maximus. Nulla tortor turpis, blandit et est in, consectetur cursus leo. Nullam non dolor lacus. Vivamus ut metus lacus. Donec neque nunc, vehicula id tincidunt non, maximus eget nulla. Morbi sed luctus justo. Etiam sit amet augue purus. Ut sodales risus at massa scelerisque faucibus. Nulla auctor, augue consectetur sodales convallis, nisi felis volutpat libero, eu rhoncus dolor metus nec lacus.

Proin mollis leo et tellus facilisis, vel ultricies orci vestibulum. Nulla vel libero nec ligula placerat cursus sit amet et elit. Duis tellus augue, viverra dapibus condimentum nec, euismod ac risus. Etiam diam nibh, aliquet nec tempor sit amet, rutrum gravida lectus. Suspendisse neque felis, rhoncus at tellus vel, egestas ultrices quam. Cras ultrices nisl viverra viverra ultrices. Vestibulum semper egestas diam, et consequat massa lacinia at. Proin feugiat et leo vitae volutpat. Etiam est tortor, pharetra sed fermentum sed, ultrices nec felis. Vestibulum blandit venenatis magna. Fusce quis sollicitudin enim, sit amet ornare orci. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean venenatis enim pulvinar, laoreet tellus vitae, feugiat felis. Nunc et finibus quam, nec pharetra tellus. Nunc quis lobortis felis. Nulla sodales enim turpis, vel auctor diam facilisis ut.

Cras viverra magna sed dolor eleifend, sit amet tempus nunc consequat. Proin id sollicitudin mauris. Maecenas a maximus mi. Sed gravida ipsum ut quam suscipit tincidunt. Curabitur ut ante et leo placerat malesuada. Donec accumsan arcu placerat sapien egestas malesuada. Curabitur ullamcorper viverra lacus. Sed sed porttitor ligula. Cras nec lacus eu nunc sodales ultrices. Donec sit amet justo id odio placerat viverra sed eget felis.

Mauris sodales in diam at ultrices. Etiam dapibus facilisis est ut tempus. Aenean elit erat, scelerisque porttitor ante a, vehicula posuere dui. Aenean mollis vitae purus non vulputate. In sem nunc, facilisis ut odio in, tincidunt fringilla velit. Phasellus consequat lacus ante, sed cursus lectus egestas a. Morbi quis eros ac nisl molestie maximus quis vel nibh. Cras sagittis vestibulum ipsum, id aliquet est aliquam sit amet. Donec cursus pellentesque turpis. Quisque tincidunt velit vel sem euismod finibus. Maecenas nec condimentum lectus. Quisque tempor dui sapien, eu rutrum ipsum gravida ut. Suspendisse lacus diam, fringilla eget diam interdum, imperdiet ornare lorem. Fusce ut risus vel leo tempor ultrices.`;