# Generated by Django 4.2.1 on 2023-05-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_to_ascii_art', '0002_alter_useruploadedimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageConvertingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_to_ascii_art.useruploadedimage')),
            ],
            options={
                'verbose_name': 'Image Converting Result',
                'verbose_name_plural': 'Image Converting Results',
                'get_latest_by': ['-created_at'],
            },
        ),
    ]
