# Generated by Django 4.2.1 on 2023-05-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_to_ascii_art', '0004_imageconvertingresult_compress_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageconvertingresult',
            old_name='compress_ratio',
            new_name='compress_level',
        ),
    ]
